version: '3.8'
services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: GeneDatabase
    ports:
      - "3306:3306"
  fastapi:
    build: ./gene-info
    image: gene-info:latest
    container_name: gene-fast-app
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000